version: "3"

services:
  whoogle-search:
    image: benbusby/whoogle-search
    container_name: whoogle-search
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
